Import('*')

DebugFlag('LLVMTraceCPU')

SimObject('LLVMTraceCPU.py')
Source('llvm_insts.cc')
Source('llvm_trace_cpu.cc')
Source('llvm_trace_cpu_driver.cc')
Source('llvm_fetch_stage.cc')
Source('llvm_decode_stage.cc')
Source('llvm_rename_stage.cc')
Source('llvm_iew_stage.cc')
Source('llvm_commit_stage.cc')