Import('*')

DebugFlag('LLVMTraceCPU')
DebugFlag('LLVMBranchPredictor')

if not env['HAVE_PROTOBUF']:
    print('Require protobuf')
    assert False

ProtoBuf('TDGInstruction.proto')

SimObject('LLVMTraceCPU.py')
Source('llvm_insts.cc')
Source('llvm_inst_parser.cc')
Source('llvm_trace_cpu.cc')
Source('llvm_trace_cpu_driver.cc')
Source('llvm_fetch_stage.cc')
Source('llvm_decode_stage.cc')
Source('llvm_rename_stage.cc')
Source('llvm_iew_stage.cc')
Source('llvm_commit_stage.cc')
Source('llvm_accelerator.cc')
Source('llvm_branch_predictor.cc')