Import('*')

SimObject('GemForgeAccelerator.py', 
    sim_objects=[
        'GemForgeAccelerator',
        'GemForgeAcceleratorManager',
        'StreamEngine',
        'SpeculativePrecomputationManager',
        'IdealPrefetcher',
        'AbstractDataFlowAccelerator',
    ])
Source('gem_forge_accelerator.cc')