Import('*')

DebugFlag('StreamEngine')

ProtoBuf('StreamMessage.proto')

Source('stream_engine.cc')
Source('stream.cc')
Source('single_stream.cc')
Source('coalesced_stream.cc')
Source('stream_history.cc')
Source('stream_element.cc')
Source('stream_pattern.cc')
Source('stream_placement_manager.cc')
Source('insts.cc')