Import('*')

DebugFlag('StreamRangeSync')
DebugFlag('L0RubyStreamBase')
DebugFlag('L0RubyStreamLife')
CompoundFlag('L0RubyStream',
             ['L0RubyStreamBase', 'L0RubyStreamLife'])

DebugFlag('MLCRubyStreamBase')
DebugFlag('MLCRubyStreamLife')
DebugFlag('MLCRubyStreamReuse')
DebugFlag('MLCRubyStreamReduce')
DebugFlag('MLCRubyStrandSplit')
DebugFlag('MLCStreamLoopBound')
CompoundFlag('MLCRubyStream', [
    'MLCRubyStreamBase', 'MLCRubyStreamLife', 'MLCRubyStreamReuse',
    'MLCRubyStreamReduce', 'MLCStreamLoopBound',
    'StreamRangeSync', 'MLCRubyStrandSplit',
])
DebugFlag('LLCRubyStreamBase')
DebugFlag('LLCRubyStreamLife')
DebugFlag('LLCRubyStreamReduce')
DebugFlag('LLCRubyStreamMulticast')
DebugFlag('LLCRubyStreamStore')
DebugFlag('LLCRubyStreamNotIssue')
DebugFlag('LLCStreamMigrationController')
DebugFlag('LLCStreamLoopBound')
DebugFlag('RemoteStreamReuse')
CompoundFlag('LLCRubyStream', [
    'LLCRubyStreamBase', 'LLCRubyStreamLife', 'LLCRubyStreamReduce',
    'LLCRubyStreamMulticast', 'LLCRubyStreamStore', 'LLCStreamLoopBound',
    'StreamRangeSync',  'LLCStreamMigrationController',
    'RemoteStreamReuse',
])
CompoundFlag('RubyStreamLife',
             ['CoreRubyStreamLife', 'L0RubyStreamLife', 'MLCRubyStreamLife', 'LLCRubyStreamLife'])
DebugFlag('SlicedDynStream')

Source('DynStreamId.cc')
Source('DynStrandId.cc')
Source('DynStrandElementRangeId.cc')
Source('DynStreamAddressRange.cc')
Source('DynStreamSliceId.cc')
Source('DynStreamSliceIdVec.cc')
Source('L0StreamEngine.cc')
Source('MLCDynStream.cc')
Source('MLCDynDirectStream.cc')
Source('MLCDynIndirectStream.cc')
Source('MLCStrandManager.cc')
Source('MLCStreamNDCController.cc')
Source('MLCStreamEngine.cc')
Source('LLCStreamSlice.cc')
Source('LLCStreamElement.cc')
Source('LLCStreamRangeBuilder.cc')
Source('LLCStreamAtomicLockManager.cc')
Source('LLCStreamCommitController.cc')
Source('LLCStreamNDCController.cc')
Source('LLCStreamMigrationController.cc')
Source('LLCDynStream.cc')
Source('LLCStreamEngine.cc')
Source('StrandSplitInfo.cc')
Source('StreamRequestBuffer.cc')
Source('CacheStreamConfigureData.cc')
Source('SlicedDynStream.cc')
Source('StreamFloatPlan.cc')
Source('StreamReuseBuffer.cc')