Import('*')

DebugFlag('StreamRangeSync')
DebugFlag('L0RubyStreamBase')
DebugFlag('L0RubyStreamLife')
CompoundFlag('L0RubyStream',
             ['L0RubyStreamBase', 'L0RubyStreamLife'])

DebugFlag('MLCRubyStreamBase')
DebugFlag('MLCRubyStreamLife')
DebugFlag('MLCRubyStreamReuse')
DebugFlag('MLCRubyStreamReduce')
DebugFlag('MLCStreamLoopBound')
CompoundFlag('MLCRubyStream', [
    'MLCRubyStreamBase', 'MLCRubyStreamLife', 'MLCRubyStreamReuse',
    'MLCRubyStreamReduce', 'MLCStreamLoopBound',
    'StreamRangeSync',
])
DebugFlag('LLCRubyStreamBase')
DebugFlag('LLCRubyStreamLife')
DebugFlag('LLCRubyStreamReduce')
DebugFlag('LLCRubyStreamMulticast')
DebugFlag('LLCRubyStreamStore')
DebugFlag('LLCRubyStreamNotIssue')
DebugFlag('LLCStreamMigrationController')
DebugFlag('LLCStreamLoopBound')
CompoundFlag('LLCRubyStream', [
    'LLCRubyStreamBase', 'LLCRubyStreamLife', 'LLCRubyStreamReduce',
    'LLCRubyStreamMulticast', 'LLCRubyStreamStore',
    'LLCRubyStreamNotIssue', 'LLCStreamLoopBound',
    'StreamRangeSync',  'LLCStreamMigrationController',
])
CompoundFlag('RubyStreamLife',
             ['CoreRubyStreamLife', 'L0RubyStreamLife', 'MLCRubyStreamLife', 'LLCRubyStreamLife'])
DebugFlag('SlicedDynamicStream')

Source('DynamicStreamId.cc')
Source('DynamicStreamElementRangeId.cc')
Source('DynamicStreamAddressRange.cc')
Source('DynamicStreamSliceId.cc')
Source('DynamicStreamSliceIdVec.cc')
Source('L0StreamEngine.cc')
Source('MLCDynamicStream.cc')
Source('MLCDynamicDirectStream.cc')
Source('MLCDynamicIndirectStream.cc')
Source('MLCStreamNDCController.cc')
Source('MLCStreamEngine.cc')
Source('LLCStreamSlice.cc')
Source('LLCStreamElement.cc')
Source('LLCStreamRangeBuilder.cc')
Source('LLCStreamAtomicLockManager.cc')
Source('LLCStreamCommitController.cc')
Source('LLCStreamNDCController.cc')
Source('LLCStreamMigrationController.cc')
Source('LLCDynamicStream.cc')
Source('LLCStreamEngine.cc')
Source('StreamRequestBuffer.cc')
Source('CacheStreamConfigureData.cc')
Source('SlicedDynamicStream.cc')
