Import('*')

DebugFlag('L0RubyStreamBase')
DebugFlag('L0RubyStreamLife')
CompoundFlag('L0RubyStream',
             ['L0RubyStreamBase', 'L0RubyStreamLife'])

DebugFlag('MLCRubyStreamBase')
DebugFlag('MLCRubyStreamLife')
DebugFlag('MLCRubyStreamReuse')
CompoundFlag('MLCRubyStream',
             ['MLCRubyStreamBase', 'MLCRubyStreamLife', 'MLCRubyStreamReuse'])
DebugFlag('LLCRubyStreamBase')
DebugFlag('LLCRubyStreamLife')
DebugFlag('LLCRubyStreamReduce')
DebugFlag('LLCRubyStreamMulticast')
DebugFlag('LLCRubyStreamStore')
DebugFlag('LLCRubyStreamNotIssue')
CompoundFlag('LLCRubyStream',
             ['LLCRubyStreamBase', 'LLCRubyStreamLife', 'LLCRubyStreamReduce',
              'LLCRubyStreamMulticast', 'LLCRubyStreamStore',
              'LLCRubyStreamNotIssue'])
CompoundFlag('RubyStreamLife',
             ['CoreRubyStreamLife', 'L0RubyStreamLife', 'MLCRubyStreamLife', 'LLCRubyStreamLife'])
DebugFlag('SlicedDynamicStream')

Source('DynamicStreamId.cc')
Source('DynamicStreamSliceId.cc')
Source('DynamicStreamSliceIdVec.cc')
Source('L0StreamEngine.cc')
Source('MLCDynamicStream.cc')
Source('MLCDynamicDirectStream.cc')
Source('MLCDynamicIndirectStream.cc')
Source('MLCStreamEngine.cc')
Source('LLCStreamElement.cc')
Source('LLCDynamicStream.cc')
Source('LLCStreamEngine.cc')
Source('CacheStreamConfigureData.cc')
Source('SlicedDynamicStream.cc')
