
Import('*')

DebugFlag('StreamPUM')

Source('AffinePattern.cc')
Source('PUMCommand.cc')
Source('PUMHWConfiguration.cc')
Source('DataMoveCompiler.cc')
Source('MLCPUMManager.cc')
Source('PUMEngine.cc')