
Import('*')

DebugFlag('LLCStreamPUM')
DebugFlag('MLCStreamPUM')
CompoundFlag('StreamPUM',
             ['LLCStreamPUM', 'MLCStreamPUM'])
DebugFlag('PUMTransposeUnit')

affine_pattern = Source('AffinePattern.cc')
llc_tile_pattern = Source('LLCTilePattern.cc')
pum_command = Source('PUMCommand.cc')
Source('PUMHWConfiguration.cc')
Source('PUMTransposeUnit.cc')
data_move_compiler = Source('DataMoveCompiler.cc')
Source('MLCPUMManager.cc')
Source('PUMEngine.cc')

tdfg = ProtoBuf('TDFG.proto')

RealExecutable('pum-jitter',
               'CommandJitter.cc',
               affine_pattern,
               llc_tile_pattern,
               pum_command,
               data_move_compiler,
               tdfg.cc_file,
               '../../../../../../base/logging.cc',
               '../../../../../../base/cprintf.cc',
        #        '../../../../../../enums/OpClass.cc',
)